name: Continuous Integration

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-x64:
    name: Build & Test (Linux x64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libdbus-1-dev

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Build Release
        run: cargo build --release

  build-linux-arm64:
    name: Build & Test (Linux ARM64)
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev libdbus-1-dev

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Build Release
        run: cargo build --release

  build-macos:
    name: Build & Test (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Build Release
        run: cargo build --release

  build-windows:
    name: Build & Test (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      - name: Build Release
        run: cargo build --release
